<?php

use App\Control;
use Illuminate\Database\Seeder;

class ControlSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //EFAM de 22junio a septiembre 2023
        $controles = [
            array('paciente_id' => 15, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/06/17', 'evaluacionPie' => 'Moderado'),
array('paciente_id' => 25, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/16', 'evaluacionPie' => 'Moderado'),
array('paciente_id' => 29, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/20', 'evaluacionPie' => 'Alto'),
array('paciente_id' => 39, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/03/06', 'evaluacionPie' => 'Alto'),
array('paciente_id' => 55, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/01/16', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 77, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/02/20', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 147, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/05/22', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 167, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/04/12', 'evaluacionPie' => 'Maximo'),
array('paciente_id' => 172, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/04/17', 'evaluacionPie' => 'Alto'),
array('paciente_id' => 200, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/01/10', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 240, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/01/10', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 267, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/03/05', 'evaluacionPie' => 'Moderado'),
array('paciente_id' => 275, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/17', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 292, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/12', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 303, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/17', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 328, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/10', 'evaluacionPie' => 'Moderado'),
array('paciente_id' => 330, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/26', 'evaluacionPie' => 'Moderado'),
array('paciente_id' => 348, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/05/13', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 349, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/19', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 568, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/01', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 570, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/20', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 609, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/31', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 658, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/03/15', 'evaluacionPie' => 'Alto'),
array('paciente_id' => 695, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/01/24', 'evaluacionPie' => 'Maximo'),
array('paciente_id' => 783, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/15', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 806, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/17', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 834, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/04/12', 'evaluacionPie' => 'Maximo'),
array('paciente_id' => 868, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/01/23', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 916, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/04/16', 'evaluacionPie' => 'Alto'),
array('paciente_id' => 1063, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/05/16', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1091, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/03/07', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1101, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/29', 'evaluacionPie' => 'Moderado'),
array('paciente_id' => 1200, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/02', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1216, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/03/15', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1225, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/03/06', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1230, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/04/18', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1234, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/14', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1246, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/01/09', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1254, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/08', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1259, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/03/04', 'evaluacionPie' => 'Maximo'),
array('paciente_id' => 1370, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/03/07', 'evaluacionPie' => 'Alto'),
array('paciente_id' => 1383, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/01/25', 'evaluacionPie' => 'Alto'),
array('paciente_id' => 1394, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/03/22', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1395, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/05', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1430, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/03', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1458, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/03/05', 'evaluacionPie' => 'Alto'),
array('paciente_id' => 1477, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/30', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1520, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/22', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1558, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/19', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1576, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/03/06', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1594, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/01/25', 'evaluacionPie' => 'Alto'),
array('paciente_id' => 1680, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/24', 'evaluacionPie' => 'Moderado'),
array('paciente_id' => 1681, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/16', 'evaluacionPie' => 'Moderado'),
array('paciente_id' => 1690, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/06/29', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1698, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/01/25', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1727, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/06/04', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1729, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/27', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1737, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/30', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1861, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/12', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1900, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/14', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1971, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/05/02', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1974, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/23', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1975, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/29', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1979, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/27', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 1993, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/27', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 2002, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/03', 'evaluacionPie' => 'Moderado'),
array('paciente_id' => 2053, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/01/24', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 2102, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/01/31', 'evaluacionPie' => 'Maximo'),
array('paciente_id' => 2229, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/14', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 2232, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/04/23', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 2277, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/02/20', 'evaluacionPie' => 'Moderado'),
array('paciente_id' => 2311, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/24', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 2381, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/28', 'evaluacionPie' => 'Maximo'),
array('paciente_id' => 2388, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/12', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 2405, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/02/29', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 2440, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/06/27', 'evaluacionPie' => 'Alto'),
array('paciente_id' => 2474, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/05/14', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 2508, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/03/13', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 2534, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/05', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 2537, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/08', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 2592, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/20', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 2702, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/01/25', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 2733, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/01', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 2838, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/01', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 2860, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/14', 'evaluacionPie' => null),
array('paciente_id' => 2988, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/01/18', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 3055, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/03/28', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 3782, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/29', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 4068, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/04/12', 'evaluacionPie' => 'Moderado'),
array('paciente_id' => 4080, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/05/09', 'evaluacionPie' => 'Alto'),
array('paciente_id' => 4262, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/20', 'evaluacionPie' => 'Moderado'),
array('paciente_id' => 4282, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/06/26', 'evaluacionPie' => 'Alto'),
array('paciente_id' => 4295, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/02/22', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 4469, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/03/27', 'evaluacionPie' => 'Alto'),
array('paciente_id' => 4687, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/06/10', 'evaluacionPie' => 'Moderado'),
array('paciente_id' => 4828, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/03', 'evaluacionPie' => 'Maximo'),
array('paciente_id' => 4837, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/07/25', 'evaluacionPie' => 'Alto'),
array('paciente_id' => 4851, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/19', 'evaluacionPie' => 'Bajo'),
array('paciente_id' => 4852, 'tipo_control' => 'Enfermera', 'fecha_control' => '2024/08/08', 'evaluacionPie' => 'Bajo')
        ];
        foreach ($controles as $control) {
            Control::create($control);
        }
    }
}
