<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Control;


class ControlEfamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //EFAM de enero a marzo 2023
    $controles = [
array('paciente_id' => 2310, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/03/24', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1543, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/01/13', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2834, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/03/06', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1317, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/02/21', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 308, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/03/21', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1080, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/01/23', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2872, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/03/14', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2873, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/03/30', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1594, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/02/16', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1864, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/01/12', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2384, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/02/21', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1364, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/03/23', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 111, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/01/17', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2417, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/03/31', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1141, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/03/27', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1911, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/03/21', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 904, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/02/27', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 394, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/02/09', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1162, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/02/13', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1934, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/01/24', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 932, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/02/13', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1450, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/01/11', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1195, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/01/16', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 183, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/03/03', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2503, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/01/19', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 205, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/02/07', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1229, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/02/06', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2262, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/03/06', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2265, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/01/30', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2011, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/03/29', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2270, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/02/24', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2542, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/01/17', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 495, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/03/20', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2543, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/03/02', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 240, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/03/20', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 499, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/01/16', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 246, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/02/27', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1528, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/02/14', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2235, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/02/09', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 29, 'rEfam' => 'autConRiesgo', 'fecha_control' =>'2023/03/08', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1280, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/27', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1283, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/21', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 776, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/27', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 15, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/30', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 19, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/23', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 788, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/20', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2836, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/06', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1813, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/20', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2837, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/27', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1302, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/11', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1558, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/30', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 535, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/08', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 792, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/06', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2841, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/27', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 796, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/12', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2598, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/03', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2599, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/03', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1064, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/03', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1588, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/28', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 312, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/02', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2360, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/03', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2111, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/20', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 64, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/23', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 836, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/06', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2117, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/27', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 331, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/08', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 588, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/03', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2126, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/06', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 342, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/07', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2139, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/07', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 352, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/20', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 359, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/23', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1896, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/13', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 873, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/03', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2413, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/23', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2418, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/07', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1909, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/07', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1400, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/20', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2169, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/27', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1916, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/27', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 128, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/27', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 134, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/30', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1935, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/20', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1424, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/09', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1173, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/23', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2456, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/20', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 668, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/30', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 166, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/10', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1192, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/02', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 689, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/20', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2495, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/25', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2500, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/02', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 458, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/24', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2259, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/12', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 216, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/24', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 733, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/04', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2527, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/19', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2532, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/03/08', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2788, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/13', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2790, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/17', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1262, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/02/13', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2047, 'rEfam' => 'autSinRiesgo', 'fecha_control' =>'2023/01/04', 'observacion' => 'carga automatica primer registro' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 527, 'rEfam' => 'rDependencia', 'fecha_control' =>'2023/02/24', 'observacion' => 'carga automatica primer contrrol' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2840, 'rEfam' => 'rDependencia', 'fecha_control' =>'2023/02/23', 'observacion' => 'carga automatica primer contrrol' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2615, 'rEfam' => 'rDependencia', 'fecha_control' =>'2023/01/19', 'observacion' => 'carga automatica primer contrrol' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 584, 'rEfam' => 'rDependencia', 'fecha_control' =>'2023/01/12', 'observacion' => 'carga automatica primer contrrol' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1105, 'rEfam' => 'rDependencia', 'fecha_control' =>'2023/03/06', 'observacion' => 'carga automatica primer contrrol' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2391, 'rEfam' => 'rDependencia', 'fecha_control' =>'2023/01/30', 'observacion' => 'carga automatica primer contrrol' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1132, 'rEfam' => 'rDependencia', 'fecha_control' =>'2023/01/25', 'observacion' => 'carga automatica primer contrrol' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2451, 'rEfam' => 'rDependencia', 'fecha_control' =>'2023/03/06', 'observacion' => 'carga automatica primer contrrol' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2210, 'rEfam' => 'rDependencia', 'fecha_control' =>'2023/01/16', 'observacion' => 'carga automatica primer contrrol' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 1191, 'rEfam' => 'rDependencia', 'fecha_control' =>'2023/01/26', 'observacion' => 'carga automatica primer contrrol' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2230, 'rEfam' => 'rDependencia', 'fecha_control' =>'2023/03/23', 'observacion' => 'carga automatica primer contrrol' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 475, 'rEfam' => 'rDependencia', 'fecha_control' =>'2023/03/27', 'observacion' => 'carga automatica primer contrrol' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2281, 'rEfam' => 'rDependencia', 'fecha_control' =>'2023/03/07', 'observacion' => 'carga automatica primer contrrol' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 2544, 'rEfam' => 'rDependencia', 'fecha_control' =>'2023/02/15', 'observacion' => 'carga automatica primer contrrol' , 'tipo_control' => 'Enfermera'),
array('paciente_id' => 241, 'rEfam' => 'rDependencia', 'fecha_control' =>'2023/01/26', 'observacion' => 'carga automatica primer contrrol' , 'tipo_control' => 'Enfermera'),
];
foreach ($controles as $control) {
            Control::create($control);
        }
    }
}
