@extends('adminlte::page')

@section('title', 'REM P3: Seccion A')

@section('content')
<div class="row justify-content-center">
    <div class="card card-primary card-outline">
        <div class="card-body">
            <h4 class="card-title text-bold mb-3">
                <a class="mx-3" href="{{ url('estadisticas') }}" title="Atras">
                    <i class="fas fa-arrow-alt-circle-left" style="font-size: x-large"></i>
                    Volver
                </a>
                REM P3 - SECCIÓN A: EXISTENCIA DE POBLACIÓN EN CONTROL
            </h4>
            <div class="col-md-12 table-responsive">
                <table id="pscv" class="table table-md-responsive table-bordered">
                    <thead>
                        <tr>
                            <th class="text-center" colspan="2" rowspan="3">PROGRAMAS</th>
                            <th class="text-center" colspan="3" rowspan="2">TOTAL</th>
                            <th class="text-center" colspan="34">GRUPOS DE EDAD (en años) Y SEXO</th>
                            <th colspan="2" rowspan="2">Pueblos Originarios</th>
                            <th colspan="2" rowspan="2">Poblacion Migrantes</th>

                        </tr>
                        <tr>
                            <th nowrap="" colspan="2">0 a 4 años</th>
                            <th nowrap="" colspan="2">5 a 9 años</th>
                            <th nowrap="" colspan="2">10 a 14 años</th>
                            <th nowrap="" colspan="2">15 a 19 años</th>
                            <th nowrap="" colspan="2">20 a 24 años</th>
                            <th nowrap="" colspan="2">25 a 29 años</th>
                            <th nowrap="" colspan="2">30 a 34 años</th>
                            <th nowrap="" colspan="2">35 a 39 años</th>
                            <th nowrap="" colspan="2">40 a 44 años</th>
                            <th nowrap="" colspan="2">45 a 49 años</th>
                            <th nowrap="" colspan="2">50 a 54 años</th>
                            <th nowrap="" colspan="2">55 a 59 años</th>
                            <th nowrap="" colspan="2">60 a 64 años</th>
                            <th nowrap="" colspan="2">65 a 69 años</th>
                            <th nowrap="" colspan="2">70 a 74 años</th>
                            <th nowrap="" colspan="2">75 a 79 años</th>
                            <th nowrap="" colspan="2">80 y mas años</th>
                        </tr>
                        <tr>
                            <th>Ambos Sexos</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                            <th>Hombres</th>
                            <th>Mujeres</th>
                        </tr>

                        <tr>
                            <th rowspan="4">SÍNDROME BRONQUIAL OBSTRUCTIVA RECURRENTE (SBOR)</th>
                        <tr>
                            <th>LEVE</th>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th>MODERADO</th>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th>SEVERO</th>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th rowspan="4" nowrap ="" class ="py-5">ASMA BRONQUIAL</th>
                        <tr>
                            <th>LEVE</th>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th>MODERADO</th>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th>SEVERO</th>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th rowspan="3">ENFERMEDAD PULMONAR OBSTRUCTIVA CRÓNICA (EPOC)</th>
                        <tr>
                            <th>TIPO A</th>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th>TIPO B</th>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th nowrap="" colspan="2">OTRAS RESPIRATORIAS CRONICAS</th>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th nowrap="" colspan="2">OXIGENO DEPENDIENTE</th>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th colspan="2">ASISTENCIA VENTILATORIA NO INVASIVA O INVASIVA</th>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th nowrap="" colspan="2">FIBROSIS QUÍSTICA </th>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th nowrap="" colspan="2">EPILEPSIA</th>
                            <td>{{$epilepsia}}</td>
                            <td>{{$epilepsiaM}}</td>
                            <td>{{$epilepsiaF}}</td>
                            <td>{{$epilepsia_04M}}</td>
                            <td>{{$epilepsia_04F}}</td>
                            <td>{{$epilepsia_59M}}</td>
                            <td>{{$epilepsia_59F}}</td>
                            <td>{{$epilepsia_1014M}}</td>
                            <td>{{$epilepsia_1014F}}</td>
                            <td>{{$epilepsia_1519M}}</td>
                            <td>{{$epilepsia_1519F}}</td>
                            <td>{{$epilepsia_2024M}}</td>
                            <td>{{$epilepsia_2024F}}</td>
                            <td>{{$epilepsia_2529M}}</td>
                            <td>{{$epilepsia_2529F}}</td>
                            <td>{{$epilepsia_3034M}}</td>
                            <td>{{$epilepsia_3034F}}</td>
                            <td>{{$epilepsia_3539M}}</td>
                            <td>{{$epilepsia_3539F}}</td>
                            <td>{{$epilepsia_4044M}}</td>
                            <td>{{$epilepsia_4044F}}</td>
                            <td>{{$epilepsia_4549M}}</td>
                            <td>{{$epilepsia_4549F}}</td>
                            <td>{{$epilepsia_5054M}}</td>
                            <td>{{$epilepsia_5054F}}</td>
                            <td>{{$epilepsia_5559M}}</td>
                            <td>{{$epilepsia_5559F}}</td>
                            <td>{{$epilepsia_6064M}}</td>
                            <td>{{$epilepsia_6064F}}</td>
                            <td>{{$epilepsia_6569M}}</td>
                            <td>{{$epilepsia_6569F}}</td>
                            <td>{{$epilepsia_7074M}}</td>
                            <td>{{$epilepsia_7074F}}</td>
                            <td>{{$epilepsia_7579M}}</td>
                            <td>{{$epilepsia_7579F}}</td>
                            <td>{{$epilepsia_80M}}</td>
                            <td>{{$epilepsia_80F}}</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th nowrap="" colspan="2">GLAUCOMA</th>
                            <td>{{$glaucoma}}</td>
                            <td>{{$glaucomaM}}</td>
                            <td>{{$glaucomaF}}</td>
                            <td>{{$glaucoma_04M}}</td>
                            <td>{{$glaucoma_04F}}</td>
                            <td>{{$glaucoma_59M}}</td>
                            <td>{{$glaucoma_59F}}</td>
                            <td>{{$glaucoma_1014M}}</td>
                            <td>{{$glaucoma_1014F}}</td>
                            <td>{{$glaucoma_1519M}}</td>
                            <td>{{$glaucoma_1519F}}</td>
                            <td>{{$glaucoma_2024M}}</td>
                            <td>{{$glaucoma_2024F}}</td>
                            <td>{{$glaucoma_2529M}}</td>
                            <td>{{$glaucoma_2529F}}</td>
                            <td>{{$glaucoma_3034M}}</td>
                            <td>{{$glaucoma_3034F}}</td>
                            <td>{{$glaucoma_3539M}}</td>
                            <td>{{$glaucoma_3539F}}</td>
                            <td>{{$glaucoma_4044M}}</td>
                            <td>{{$glaucoma_4044F}}</td>
                            <td>{{$glaucoma_4549M}}</td>
                            <td>{{$glaucoma_4549F}}</td>
                            <td>{{$glaucoma_5054M}}</td>
                            <td>{{$glaucoma_5054F}}</td>
                            <td>{{$glaucoma_5559M}}</td>
                            <td>{{$glaucoma_5559F}}</td>
                            <td>{{$glaucoma_6064M}}</td>
                            <td>{{$glaucoma_6064F}}</td>
                            <td>{{$glaucoma_6569M}}</td>
                            <td>{{$glaucoma_6569F}}</td>
                            <td>{{$glaucoma_7074M}}</td>
                            <td>{{$glaucoma_7074F}}</td>
                            <td>{{$glaucoma_7579M}}</td>
                            <td>{{$glaucoma_7579F}}</td>
                            <td>{{$glaucoma_80M}}</td>
                            <td>{{$glaucoma_80F}}</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th nowrap="" colspan="2">ENFERMEDAD DE PARKINSON </th>
                            <td>{{$parkinson}}</td>
                            <td>{{$parkinsonM}}</td>
                            <td>{{$parkinsonF}}</td>
                            <td>{{$parkinson_04M}}</td>
                            <td>{{$parkinson_04F}}</td>
                            <td>{{$parkinson_59M}}</td>
                            <td>{{$parkinson_59F}}</td>
                            <td>{{$parkinson_1014M}}</td>
                            <td>{{$parkinson_1014F}}</td>
                            <td>{{$parkinson_1519M}}</td>
                            <td>{{$parkinson_1519F}}</td>
                            <td>{{$parkinson_2024M}}</td>
                            <td>{{$parkinson_2024F}}</td>
                            <td>{{$parkinson_2529M}}</td>
                            <td>{{$parkinson_2529F}}</td>
                            <td>{{$parkinson_3034M}}</td>
                            <td>{{$parkinson_3034F}}</td>
                            <td>{{$parkinson_3539M}}</td>
                            <td>{{$parkinson_3539F}}</td>
                            <td>{{$parkinson_4044M}}</td>
                            <td>{{$parkinson_4044F}}</td>
                            <td>{{$parkinson_4549M}}</td>
                            <td>{{$parkinson_4549F}}</td>
                            <td>{{$parkinson_5054M}}</td>
                            <td>{{$parkinson_5054F}}</td>
                            <td>{{$parkinson_5559M}}</td>
                            <td>{{$parkinson_5559F}}</td>
                            <td>{{$parkinson_6064M}}</td>
                            <td>{{$parkinson_6064F}}</td>
                            <td>{{$parkinson_6569M}}</td>
                            <td>{{$parkinson_6569F}}</td>
                            <td>{{$parkinson_7074M}}</td>
                            <td>{{$parkinson_7074F}}</td>
                            <td>{{$parkinson_7579M}}</td>
                            <td>{{$parkinson_7579F}}</td>
                            <td>{{$parkinson_80M}}</td>
                            <td>{{$parkinson_80F}}</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th nowrap="" colspan="2">ARTROSIS DE CADERA Y RODILLA</th>
                            <td>{{$artrosis}}</td>
                            <td>{{$artrosisM}}</td>
                            <td>{{$artrosisF}}</td>
                            <td>{{$artrosis_04M}}</td>
                            <td>{{$artrosis_04F}}</td>
                            <td>{{$artrosis_59M}}</td>
                            <td>{{$artrosis_59F}}</td>
                            <td>{{$artrosis_1014M}}</td>
                            <td>{{$artrosis_1014F}}</td>
                            <td>{{$artrosis_1519M}}</td>
                            <td>{{$artrosis_1519F}}</td>
                            <td>{{$artrosis_2024M}}</td>
                            <td>{{$artrosis_2024F}}</td>
                            <td>{{$artrosis_2529M}}</td>
                            <td>{{$artrosis_2529F}}</td>
                            <td>{{$artrosis_3034M}}</td>
                            <td>{{$artrosis_3034F}}</td>
                            <td>{{$artrosis_3539M}}</td>
                            <td>{{$artrosis_3539F}}</td>
                            <td>{{$artrosis_4044M}}</td>
                            <td>{{$artrosis_4044F}}</td>
                            <td>{{$artrosis_4549M}}</td>
                            <td>{{$artrosis_4549F}}</td>
                            <td>{{$artrosis_5054M}}</td>
                            <td>{{$artrosis_5054F}}</td>
                            <td>{{$artrosis_5559M}}</td>
                            <td>{{$artrosis_5559F}}</td>
                            <td>{{$artrosis_6064M}}</td>
                            <td>{{$artrosis_6064F}}</td>
                            <td>{{$artrosis_6569M}}</td>
                            <td>{{$artrosis_6569F}}</td>
                            <td>{{$artrosis_7074M}}</td>
                            <td>{{$artrosis_7074F}}</td>
                            <td>{{$artrosis_7579M}}</td>
                            <td>{{$artrosis_7579F}}</td>
                            <td>{{$artrosis_80M}}</td>
                            <td>{{$artrosis_80F}}</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th nowrap="" colspan="2">ALIVIO DEL DOLOR</th>
                            <td>{{$alivio_dolor}}</td>
                            <td>{{$alivio_dolorM}}</td>
                            <td>{{$alivio_dolorF}}</td>
                            <td>{{$alivio_dolor_04M}}</td>
                            <td>{{$alivio_dolor_04F}}</td>
                            <td>{{$alivio_dolor_59M}}</td>
                            <td>{{$alivio_dolor_59F}}</td>
                            <td>{{$alivio_dolor_1014M}}</td>
                            <td>{{$alivio_dolor_1014F}}</td>
                            <td>{{$alivio_dolor_1519M}}</td>
                            <td>{{$alivio_dolor_1519F}}</td>
                            <td>{{$alivio_dolor_2024M}}</td>
                            <td>{{$alivio_dolor_2024F}}</td>
                            <td>{{$alivio_dolor_2529M}}</td>
                            <td>{{$alivio_dolor_2529F}}</td>
                            <td>{{$alivio_dolor_3034M}}</td>
                            <td>{{$alivio_dolor_3034F}}</td>
                            <td>{{$alivio_dolor_3539M}}</td>
                            <td>{{$alivio_dolor_3539F}}</td>
                            <td>{{$alivio_dolor_4044M}}</td>
                            <td>{{$alivio_dolor_4044F}}</td>
                            <td>{{$alivio_dolor_4549M}}</td>
                            <td>{{$alivio_dolor_4549F}}</td>
                            <td>{{$alivio_dolor_5054M}}</td>
                            <td>{{$alivio_dolor_5054F}}</td>
                            <td>{{$alivio_dolor_5559M}}</td>
                            <td>{{$alivio_dolor_5559F}}</td>
                            <td>{{$alivio_dolor_6064M}}</td>
                            <td>{{$alivio_dolor_6064F}}</td>
                            <td>{{$alivio_dolor_6569M}}</td>
                            <td>{{$alivio_dolor_6569F}}</td>
                            <td>{{$alivio_dolor_7074M}}</td>
                            <td>{{$alivio_dolor_7074F}}</td>
                            <td>{{$alivio_dolor_7579M}}</td>
                            <td>{{$alivio_dolor_7579F}}</td>
                            <td>{{$alivio_dolor_80M}}</td>
                            <td>{{$alivio_dolor_80F}}</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th nowrap="" colspan="2">HIPOTIROIDISMO</th>
                            <td>{{$hipot}}</td>
                            <td>{{$hipotM}}</td>
                            <td>{{$hipotF}}</td>
                            <td>{{$hipot_04M}}</td>
                            <td>{{$hipot_04F}}</td>
                            <td>{{$hipot_59M}}</td>
                            <td>{{$hipot_59F}}</td>
                            <td>{{$hipot_1014M}}</td>
                            <td>{{$hipot_1014F}}</td>
                            <td>{{$hipot_1519M}}</td>
                            <td>{{$hipot_1519F}}</td>
                            <td>{{$hipot_2024M}}</td>
                            <td>{{$hipot_2024F}}</td>
                            <td>{{$hipot_2529M}}</td>
                            <td>{{$hipot_2529F}}</td>
                            <td>{{$hipot_3034M}}</td>
                            <td>{{$hipot_3034F}}</td>
                            <td>{{$hipot_3539M}}</td>
                            <td>{{$hipot_3539F}}</td>
                            <td>{{$hipot_4044M}}</td>
                            <td>{{$hipot_4044F}}</td>
                            <td>{{$hipot_4549M}}</td>
                            <td>{{$hipot_4549F}}</td>
                            <td>{{$hipot_5054M}}</td>
                            <td>{{$hipot_5054F}}</td>
                            <td>{{$hipot_5559M}}</td>
                            <td>{{$hipot_5559F}}</td>
                            <td>{{$hipot_6064M}}</td>
                            <td>{{$hipot_6064F}}</td>
                            <td>{{$hipot_6569M}}</td>
                            <td>{{$hipot_6569F}}</td>
                            <td>{{$hipot_7074M}}</td>
                            <td>{{$hipot_7074F}}</td>
                            <td>{{$hipot_7579M}}</td>
                            <td>{{$hipot_7579F}}</td>
                            <td>{{$hipot_80M}}</td>
                            <td>{{$hipot_80F}}</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th nowrap="" colspan="2">DEPENDENCIA LEVE</th>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th nowrap="" colspan="2">DEPENDENCIA MODERADA</th>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
